site_name: AppDoc Documentation
site_description: Multi-language code documentation analysis tool
site_author: AppDoc Team

repo_name: HeWhoRoams/AppDoc
repo_url: https://github.com/HeWhoRoams/AppDoc

theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Usage: usage.md
  - Developer Guide: dev-guide.md
  - Architecture: architecture.md
  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
