#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Compatibility wrapper for architecture diagram generation.

.DESCRIPTION
    This script is intentionally thin and delegates all work to
    generate-mermaid-architecture-suite.ps1 so the diagram pipeline
    has a single deterministic extraction/render path.
#>

param(
    [Parameter(Mandatory=$false)]
    [string]$RootPath = ".",
    [Parameter(Mandatory=$false)]
    [switch]$ExportJson,
    [Parameter(Mandatory=$false)]
    [switch]$SkipC4
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$suiteScript = Join-Path $PSScriptRoot "generate-mermaid-architecture-suite.ps1"
if (-not (Test-Path $suiteScript)) {
    Write-Error "Required script not found: $suiteScript"
    exit 1
}

if ($ExportJson) {
    Write-Warning "-ExportJson is deprecated and ignored. Diagram truth pack JSON is always generated by the canonical suite."
}

Write-Host "generate-architecture-diagram.ps1 is a compatibility wrapper. Delegating to generate-mermaid-architecture-suite.ps1." -ForegroundColor Yellow
& $suiteScript -RootPath $RootPath -SkipC4:$SkipC4
exit $LASTEXITCODE
