#
# generate-docs-index.ps1
#
# Purpose: Generates a navigation index for all documentation artifacts. Creates a landing page
#          with links to all generated documentation files, making it easy for users to discover
#          and navigate the documentation set.
#
# Usage: .\generate-docs-index.ps1 -RootPath <target_codebase_path>
# Output: Writes to AppDoc/docs/index.md (relative to RootPath)
#

param(
    [Parameter(Mandatory=$true)]
    [string]$RootPath
)

Write-Host "📑 Generating Documentation Index..." -ForegroundColor Cyan

# Validate root path
if (-not (Test-Path $RootPath)) {
    Write-Error "Root path does not exist: $RootPath"
    exit 1
}

Write-Progress -Activity "Generating Documentation Index" -Status "Reviewing artifacts..." -PercentComplete 0

$docsPath = Join-Path $RootPath "docs"
$artifacts = @(
    @{ File = "start-here.md"; Title = "Start Here"; Description = "Role-based onboarding and broad-to-deep reading paths" },
    @{ File = "overview.md"; Title = "System Overview"; Description = "High-level codebase summary" },
    @{ File = "api-inventory.md"; Title = "API Inventory"; Description = "All API endpoints and contracts" },
    @{ File = "data-model.md"; Title = "Data Model"; Description = "Data structures and relationships" },
    @{ File = "config-catalog.md"; Title = "Configuration Catalog"; Description = "All configuration options" },
    @{ File = "build-cookbook.md"; Title = "Build Cookbook"; Description = "Build and deployment commands" },
    @{ File = "test-catalog.md"; Title = "Test Catalog"; Description = "Test suites and cases" },
    @{ File = "task-guides.md"; Title = "Task Guides"; Description = "Task-centric implementation and operations playbooks" },
    @{ File = "debt-register.md"; Title = "Technical Debt Register"; Description = "Known technical debt items" },
    @{ File = "dependencies-catalog.md"; Title = "Dependencies Catalog"; Description = "External and internal dependencies with version risks" }
)

$markdown = "# Documentation Index`n`n"
$markdown += "**Generated**: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`n`n"
$markdown += "## Reader Paths`n`n"
$markdown += "### Operate`n"
$markdown += "- **When to read**: You need to run, troubleshoot, or support the system.`n"
$markdown += "- **What you'll learn**: startup commands, runtime config, test/verification hooks, operational risks.`n"
$markdown += "- **Estimated read time**: 12-15 minutes.`n"
$markdown += "- **Start with**: [Start Here](start-here.md), [Build Cookbook](build-cookbook.md), [Configuration Catalog](config-catalog.md), [Dependencies Catalog](dependencies-catalog.md)`n`n"

$markdown += "### Change Code`n"
$markdown += "- **When to read**: You are implementing or modifying behavior.`n"
$markdown += "- **What you'll learn**: API surface, data contracts, test coverage, task-level implementation guides.`n"
$markdown += "- **Estimated read time**: 15-20 minutes.`n"
$markdown += "- **Start with**: [API Inventory](api-inventory.md), [Data Model](data-model.md), [Test Catalog](test-catalog.md), [Task Guides](task-guides.md)`n`n"

$markdown += "### Architecture`n"
$markdown += "- **When to read**: You need system boundaries, integration shape, and modernization priorities.`n"
$markdown += "- **What you'll learn**: architecture style, runtime path, external dependencies, debt hotspots.`n"
$markdown += "- **Estimated read time**: 10-15 minutes.`n"
if (Test-Path (Join-Path $docsPath 'diagrams/index.md')) {
    $markdown += "- **Start with**: [System Overview](overview.md), [Diagram Index](diagrams/index.md), [Technical Debt Register](debt-register.md)`n`n"
} else {
    $markdown += "- **Start with**: [System Overview](overview.md), [Technical Debt Register](debt-register.md)`n`n"
    Write-Warning "diagrams/index.md not found; skipping link in index."
}

$markdown += "## Artifact Catalog`n`n"

$foundCount = 0
foreach ($artifact in $artifacts) {
    $path = Join-Path $docsPath $artifact.File
    if (Test-Path $path) {
        $markdown += "### [$($artifact.Title)]($($artifact.File))`n"
        $markdown += "$($artifact.Description)`n`n"
        $foundCount++
    }
}

if ($foundCount -eq 0) {
    $markdown += "_No documentation artifacts found yet. Run the AppDoc workflow to generate documentation._`n`n"
}

$markdown += "---`n`n"
$markdown += "**Total Documents**: $foundCount / $($artifacts.Count)`n`n"
$markdown += "**Generated by AppDoc Framework**`n"

Write-Progress -Activity "Generating Documentation Index" -Status "Creating index..." -PercentComplete 50

$indexPath = Join-Path $docsPath "index.md"
$markdown | Out-File -FilePath $indexPath -Encoding UTF8

Write-Progress -Activity "Generating Documentation Index" -Status "Complete" -PercentComplete 100
Write-Host "✅ Documentation index generated: $indexPath" -ForegroundColor Green
Write-Host "   Documents indexed: $foundCount / $($artifacts.Count)" -ForegroundColor Gray
