# Simple README generator
param(
    [string]$RootPath = (Get-Location).Path,
    [string]$Output = "README.md"
)

Write-Host "Generating README.md..." -ForegroundColor Cyan
Write-Host ""

# Extract project metadata
$projectName = Split-Path $RootPath -Leaf
$description = ""
$version = "0.1.0"
$author = ""
$license = "MIT"

# Try to read package.json
$packageJsonPath = Join-Path $RootPath "package.json"
if (Test-Path $packageJsonPath) {
    $pkg = Get-Content $packageJsonPath | ConvertFrom-Json
    $projectName = if ($pkg.name) { $pkg.name } else { $projectName }
    $description = if ($pkg.description) { $pkg.description } else { "" }
    $version = if ($pkg.version) { $pkg.version } else { $version }
    $author = if ($pkg.author) { $pkg.author } else { "" }
    $license = if ($pkg.license) { $pkg.license } else { $license }

    Write-Host "Found package.json" -ForegroundColor Green
    Write-Host "  Project: $projectName" -ForegroundColor Gray
    Write-Host "  Version: $version" -ForegroundColor Gray
}

# Find TypeScript/JavaScript files for examples
$codeFiles = Get-ChildItem -Path $RootPath -Include *.ts,*.js -Recurse -File |
    Where-Object { $_.FullName -notmatch 'node_modules|dist|build|\.git|test|spec' } |
    Select-Object -First 3

Write-Host "Found $($codeFiles.Count) code files for examples" -ForegroundColor Green

# Extract a simple export for example
$exampleCode = ""
foreach ($file in $codeFiles) {
    $content = Get-Content $file.FullName -Raw
    $exportMatch = [regex]::Match($content, 'export\s+(function|class|const)\s+(\w+)')
    if ($exportMatch.Success) {
        $exportType = $exportMatch.Groups[1].Value
        $exportName = $exportMatch.Groups[2].Value
        $exampleCode = "import { $exportName } from '$projectName';"
        break
    }
}

# Check for scripts in package.json
$scripts = @()
if (Test-Path $packageJsonPath) {
    $pkg = Get-Content $packageJsonPath | ConvertFrom-Json
    if ($pkg.scripts) {
        $pkg.scripts.PSObject.Properties | ForEach-Object {
            $scripts += @{ Name = $_.Name; Command = $_.Value }
        }
    }
}

# Generate README
$readme = @"
# $projectName

$description

## Installation

``````bash
npm install $projectName
``````

## Quick Start

``````typescript
$exampleCode

// Your code here
``````

## Usage

### Basic Example

``````typescript
// Add usage examples here
``````

## Configuration

Configuration options will be documented here.

## Available Scripts

"@

if ($scripts.Count -gt 0) {
    foreach ($script in $scripts) {
        $readme += "`n- **$($script.Name)**: ``$($script.Command)``"
    }
} else {
    $readme += "`n- Run ``npm test`` to run tests"
    $readme += "`n- Run ``npm run build`` to build"
}

$readme += @"


## API Reference

API documentation will be added here.

## Contributing

Contributions are welcome! Please:

1. Fork the repository
2. Create a feature branch
3. Make your changes
4. Submit a pull request

## License

This project is licensed under the $license License.

## Support

For support, please open an issue on GitHub.

---

Generated by AppDoc Framework
"@

# Save README
$outputPath = Join-Path $RootPath $Output
$readme | Out-File -FilePath $outputPath -Encoding UTF8

Write-Host ""
Write-Host "README.md generated successfully!" -ForegroundColor Green
Write-Host "Location: $outputPath" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Review and customize the generated content"
Write-Host "  2. Add specific usage examples"
Write-Host "  3. Fill in API reference section"

