param(
    [Parameter(Mandatory=$false)]
    [string]$RootPath = "."
)

Write-Host "📊 Generating Documentation Assessment Report..." -ForegroundColor Cyan

$docsPath = Join-Path $RootPath "docs"
if (-not (Test-Path $docsPath)) {
    Write-Warning "Docs directory not found at: $docsPath"
    exit 1
}

# Gather metrics from generated docs
$docFiles = Get-ChildItem -Path $docsPath -Filter "*.md" -ErrorAction SilentlyContinue
$totalSize = ($docFiles | Measure-Object -Property Length -Sum).Sum

# Analyze each document
$docMetrics = @()
foreach ($doc in $docFiles) {
    $content = Get-Content $doc.FullName -Raw -ErrorAction SilentlyContinue
    if ($content) {
        $lineCount = ($content -split "`n").Count
        $hasContent = $content.Length -gt 1000  # More than just template
        
        $docMetrics += @{
            Name = $doc.Name
            SizeKB = [math]::Round($doc.Length / 1KB, 2)
            Lines = $lineCount
            HasContent = $hasContent
        }
    }
}

# Generate report
$report = @"
# Documentation Assessment Report

**Generated**: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

## Summary

- **Total Documents**: $($docFiles.Count)
- **Total Size**: $([math]::Round($totalSize / 1KB, 2)) KB
- **Documents with Content**: $(($docMetrics | Where-Object { $_.HasContent }).Count)
- **Template-Only Documents**: $(($docMetrics | Where-Object { -not $_.HasContent }).Count)

## Documentation Coverage

| Document | Size (KB) | Lines | Status |
|----------|-----------|-------|--------|
"@

foreach ($metric in ($docMetrics | Sort-Object Name)) {
    $status = if ($metric.HasContent) { "✅ Content" } else { "⚠️ Template Only" }
    $report += "`n| $($metric.Name) | $($metric.SizeKB) | $($metric.Lines) | $status |"
}

$report += @"


## Quality Metrics

- **Average Document Size**: $([math]::Round(($docMetrics | Measure-Object -Property SizeKB -Average).Average, 2)) KB
- **Largest Document**: $(($docMetrics | Sort-Object SizeKB -Descending | Select-Object -First 1).Name) ($((($docMetrics | Sort-Object SizeKB -Descending | Select-Object -First 1).SizeKB)) KB)
- **Smallest Document**: $(($docMetrics | Sort-Object SizeKB | Select-Object -First 1).Name) ($((($docMetrics | Sort-Object SizeKB | Select-Object -First 1).SizeKB)) KB)

## Recommendations

"@

$emptyDocs = $docMetrics | Where-Object { -not $_.HasContent }
if ($emptyDocs.Count -gt 0) {
    $report += "### Documents Needing Content`n`n"
    $report += "The following documents appear to contain only template content:`n`n"
    foreach ($doc in $emptyDocs) {
        $report += "- **$($doc.Name)** - Review generators or codebase patterns`n"
    }
    $report += "`n"
} else {
    $report += "✅ All documents have been populated with content.`n`n"
}

$report += @"

### Next Steps

1. Review documents marked as "Template Only"
2. Verify cross-references between documents are accurate
3. Update any [NEEDS_CLARIFICATION] markers with specific details
4. Consider adding examples or diagrams where applicable

---

**Generated by AppDoc Framework**
"@

$reportPath = Join-Path $docsPath "assessment-report.md"
$report | Out-File -FilePath $reportPath -Encoding UTF8

Write-Host "✅ Assessment report generated: $reportPath" -ForegroundColor Green
Write-Host "   Documents analyzed: $($docFiles.Count)" -ForegroundColor Gray

