# Simple Mermaid diagram generator
param(
    [string]$RootPath = (Get-Location).Path,
    [ValidateSet('class', 'module', 'sequence')]
    [string]$Type = 'class',
    [string]$Output = "docs/diagrams/architecture.md"
)

Write-Host "Generating $Type diagram..." -ForegroundColor Cyan
Write-Host ""

# Find TypeScript/JavaScript files
$codeFiles = Get-ChildItem -Path $RootPath -Include *.ts,*.js -Recurse -File |
    Where-Object { $_.FullName -notmatch 'node_modules|dist|build|\.git|test|spec' }

Write-Host "Analyzing $($codeFiles.Count) files..." -ForegroundColor Green

if ($Type -eq 'class') {
    # Generate class diagram
    $classes = @()
    $relationships = @()

    foreach ($file in $codeFiles) {
        $content = Get-Content $file.FullName -Raw

        # Find classes
        $classMatches = [regex]::Matches($content, '(export\s+)?(class|interface)\s+(\w+)(\s+extends\s+(\w+))?')
        foreach ($match in $classMatches) {
            $className = $match.Groups[3].Value
            $extendsClass = $match.Groups[5].Value

            if ($className) {
                # Find methods in this class (simple approach)
                $classContent = $content.Substring($match.Index, [Math]::Min(1000, $content.Length - $match.Index))
                $methods = [regex]::Matches($classContent, '(\w+)\s*\([^)]*\)\s*[:{]')

                $classMethods = @()
                foreach ($method in $methods | Select-Object -First 5) {
                    $methodName = $method.Groups[1].Value
                    if ($methodName -ne $className -and $methodName -ne 'constructor') {
                        $classMethods += $methodName
                    }
                }

                $classes += @{
                    Name = $className
                    Methods = $classMethods
                    File = $file.Name
                }

                if ($extendsClass) {
                    $relationships += "$extendsClass <|-- $className"
                }
            }
        }
    }

    Write-Host "Found $($classes.Count) classes" -ForegroundColor Green

    # Build Mermaid class diagram
    $diagram = "classDiagram`n"

    foreach ($class in $classes) {
        $diagram += "    class $($class.Name) {`n"
        foreach ($method in $class.Methods) {
            $diagram += "        +$method()`n"
        }
        $diagram += "    }`n"
    }

    foreach ($rel in $relationships) {
        $diagram += "    $rel`n"
    }

} elseif ($Type -eq 'module') {
    # Generate module dependency diagram
    $modules = @()
    $imports = @()

    foreach ($file in $codeFiles) {
        $content = Get-Content $file.FullName -Raw
        $moduleName = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)

        # Find imports
        $importMatches = [regex]::Matches($content, "import.*from\s+['\""](\.\.?/[^'""]+|@?[\w/-]+)['""]")
        foreach ($match in $importMatches) {
            $importPath = $match.Groups[1].Value
            $importModule = if ($importPath -match '\.\.?/') {
                [System.IO.Path]::GetFileNameWithoutExtension($importPath)
            } else {
                $importPath -replace '@/', ''
            }
            $imports += "$moduleName --> $importModule"
        }

        $modules += $moduleName
    }

    Write-Host "Found $($modules.Count) modules with $($imports.Count) dependencies" -ForegroundColor Green

    # Build Mermaid flowchart
    $diagram = "graph TD`n"
    foreach ($module in $modules | Select-Object -First 20) {
        $diagram += "    $module[$module]`n"
    }
    foreach ($import in $imports | Select-Object -Unique -First 30) {
        $diagram += "    $import`n"
    }

} else {
    # Sequence diagram (simple example)
    $diagram = @"
sequenceDiagram
    participant User
    participant API
    participant Database

    User->>API: Request data
    API->>Database: Query
    Database-->>API: Results
    API-->>User: Response
"@
}

# Save diagram
$outputPath = Join-Path $RootPath $Output
$outputDir = Split-Path $outputPath -Parent
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$diagramDoc = @"
# Architecture Diagram

Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

## $($Type.ToUpper()) Diagram

``````mermaid
$diagram
``````

## How to View

1. Copy the Mermaid code above
2. Paste into a Markdown file
3. View in VSCode with Mermaid extension
4. Or use https://mermaid.live to render

---
Generated by AppDoc Framework
"@

$diagramDoc | Out-File -FilePath $outputPath -Encoding UTF8

Write-Host ""
Write-Host "Diagram generated successfully!" -ForegroundColor Green
Write-Host "Location: $outputPath" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. View diagram in VSCode with Mermaid extension"
Write-Host "  2. Or paste into https://mermaid.live"
Write-Host "  3. Customize relationships and layout"

