<#
.SYNOPSIS
    Generates C4 architecture diagrams in Mermaid format.

.DESCRIPTION
    Analyzes a .NET solution and generates Mermaid-based C4 diagrams
    (System Context and Container) as Markdown files in docs/diagrams.

.PARAMETER CodebasePath
    Path to the solution file (.sln) or codebase directory.

.PARAMETER OutputPath
    Output directory for generated documentation artifacts. Defaults to 'docs'.

.PARAMETER DiagramLevels
    Which C4 diagram levels to generate: 'Context', 'Container', or 'All'.

.PARAMETER Force
    Force regeneration of diagrams even if output files already exist.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]$CodebasePath,

    [Parameter(Mandatory=$false)]
    [string]$OutputPath = "docs",

    [Parameter(Mandatory=$false)]
    [ValidateSet('Context', 'Container', 'All')]
    [string]$DiagramLevels = 'All',

    [Parameter(Mandatory=$false)]
    [switch]$Force
)

$modulesPath = Join-Path $PSScriptRoot "modules"
Import-Module (Join-Path $modulesPath "C4ModelBuilder.psm1") -Force

function ConvertTo-MermaidNodeId {
    param([string]$Text)

    if (-not $Text) { return "node" }
    $normalized = $Text.ToLower() -replace '[^a-z0-9_]', '_'
    if ($normalized -match '^[0-9]') {
        return "n_$normalized"
    }
    return $normalized
}

function New-ContextMermaid {
    param(
        [Parameter(Mandatory=$true)]
        [hashtable]$SystemModel
    )

    $systemId = ConvertTo-MermaidNodeId -Text $SystemModel.Id
    $lines = @(
        "graph LR"
        "    user[`"User`"]"
        "    $systemId[`"$($SystemModel.Name)`"]"
        "    user -->|Uses| $systemId"
    )

    foreach ($ext in @($SystemModel.ExternalSystems)) {
        $extId = ConvertTo-MermaidNodeId -Text $ext.Id
        $lines += "    $extId[`"$($ext.Name)`"]"
        $lines += "    $systemId -->|Integrates with| $extId"
    }

    return ($lines -join "`n")
}

function New-ContainerMermaid {
    param(
        [Parameter(Mandatory=$true)]
        [hashtable]$ContainerModel
    )

    $lines = @(
        "graph LR"
    )

    foreach ($container in @($ContainerModel.Containers)) {
        $containerId = ConvertTo-MermaidNodeId -Text $container.Id
        $lines += "    $containerId[`"$($container.Name)`n$($container.Technology)`"]"
    }

    foreach ($rel in @($ContainerModel.Relationships)) {
        $sourceId = ConvertTo-MermaidNodeId -Text $rel.Source
        $targetId = ConvertTo-MermaidNodeId -Text $rel.Target
        $label = if ($rel.Description) { $rel.Description } else { "Uses" }
        $lines += "    $sourceId -->|$label| $targetId"
    }

    if ($ContainerModel.Containers.Count -eq 0) {
        $lines += "    no_containers[`"No deployable containers detected`"]"
    }

    return ($lines -join "`n")
}

function Save-MermaidMarkdown {
    param(
        [Parameter(Mandatory=$true)]
        [string]$FilePath,
        [Parameter(Mandatory=$true)]
        [string]$Title,
        [Parameter(Mandatory=$true)]
        [string]$Mermaid,
        [Parameter(Mandatory=$true)]
        [string[]]$Summary
    )

    $directory = Split-Path -Parent $FilePath
    if (-not (Test-Path $directory)) {
        New-Item -Path $directory -ItemType Directory -Force | Out-Null
    }

    $summaryBullets = $Summary | ForEach-Object { "- $_" }
    $markdownLines = @()
    $markdownLines += "# $Title"
    $markdownLines += ''
    $markdownLines += "**Generated**: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    $markdownLines += ''
    $markdownLines += '## Summary'
    $markdownLines += ''
    $markdownLines += $summaryBullets
    $markdownLines += ''
    $markdownLines += '## Diagram'
    $markdownLines += ''
    $markdownLines += '```mermaid'
    $markdownLines += $Mermaid
    $markdownLines += '```'
    $markdownLines += ''
    $markdownLines += '---'
    $markdownLines += ''
    $markdownLines += '**Generated by AppDoc Framework**'
    $markdown = $markdownLines -join "`n"

    $markdown | Out-File -FilePath $FilePath -Encoding UTF8 -NoNewline
}

function Update-OverviewArchitectureSection {
    param(
        [Parameter(Mandatory=$true)]
        [string]$OverviewPath,
        [Parameter(Mandatory=$true)]
        [string[]]$References
    )

    if (-not (Test-Path $OverviewPath)) {
        return
    }

    $content = Get-Content -Path $OverviewPath -Raw
    $architectureSection = @(
        "## Architecture",
        "",
        "Generated C4 Mermaid diagrams:",
        ""
    ) + ($References | ForEach-Object { "- $_" })

    $sectionText = $architectureSection -join "`n"

    if ($content -match '(?s)##\s+Architecture\s*.*?(?=\n##\s+[^\n]+|\z)') {
        $content = [regex]::Replace($content, '(?s)##\s+Architecture\s*.*?(?=\n##\s+[^\n]+|\z)', $sectionText)
    }
    else {
        $content = $content.TrimEnd() + "`n`n" + $sectionText + "`n"
    }

    $content | Out-File -FilePath $OverviewPath -Encoding UTF8 -NoNewline
}

Write-Host "=== AppDoc Mermaid C4 Diagram Generator ===" -ForegroundColor Cyan
Write-Host "Codebase: $CodebasePath"
Write-Host "Output: $OutputPath"
Write-Host ""

if (-not (Test-Path $CodebasePath)) {
    Write-Error "Codebase path not found: $CodebasePath"
    exit 1
}

$diagramsPath = Join-Path $OutputPath "diagrams"
if (-not (Test-Path $diagramsPath)) {
    New-Item -Path $diagramsPath -ItemType Directory -Force | Out-Null
}

$solutionFile = $null
if ($CodebasePath -like "*.sln") {
    $solutionFile = $CodebasePath
}
else {
    $slnFiles = Get-ChildItem -Path $CodebasePath -Filter "*.sln" -File -Recurse -ErrorAction SilentlyContinue
    if ($slnFiles.Count -eq 0) {
        Write-Warning "No solution file found in: $CodebasePath. Generating placeholder Mermaid diagrams."
        $generatedFiles = @()
        if ($DiagramLevels -in @('Context', 'All')) {
            $contextOutput = Join-Path $diagramsPath "c4-context.md"
            Save-MermaidMarkdown -FilePath $contextOutput -Title "C4 System Context" -Mermaid "graph LR`n    system[`"System`"]" -Summary @(
                "System detection unavailable (no solution file found)",
                "External systems detected: 0",
                "Scope: high-level system context"
            )
            $generatedFiles += "[C4 Context](diagrams/c4-context.md)"
        }

        if ($DiagramLevels -in @('Container', 'All')) {
            $containerOutput = Join-Path $diagramsPath "c4-container.md"
            Save-MermaidMarkdown -FilePath $containerOutput -Title "C4 Container" -Mermaid "graph LR`n    no_containers[`"No deployable containers detected`"]" -Summary @(
                "System detection unavailable (no solution file found)",
                "Containers detected: 0",
                "Relationships detected: 0"
            )
            $generatedFiles += "[C4 Container](diagrams/c4-container.md)"
        }

        $overviewPath = Join-Path $OutputPath "overview.md"
        if ($generatedFiles.Count -gt 0) {
            Update-OverviewArchitectureSection -OverviewPath $overviewPath -References $generatedFiles
        }

        Write-Host "✓ Mermaid C4 placeholder diagram generation complete" -ForegroundColor Green
        exit 0
    }

    $solutionFile = $slnFiles[0].FullName
    Write-Host "Found solution: $($slnFiles[0].Name)" -ForegroundColor Green
}

$generatedFiles = @()

if ($DiagramLevels -in @('Context', 'All')) {
    $contextOutput = Join-Path $diagramsPath "c4-context.md"
    if ((Test-Path $contextOutput) -and -not $Force) {
        Write-Host "Context diagram already exists (use -Force to regenerate)" -ForegroundColor Gray
    }
    else {
        $systemModel = Build-SystemContextModel -SolutionPath $solutionFile
        if ($systemModel) {
            $mermaid = New-ContextMermaid -SystemModel $systemModel
            Save-MermaidMarkdown -FilePath $contextOutput -Title "C4 System Context" -Mermaid $mermaid -Summary @(
                "System: $($systemModel.Name)",
                "External systems detected: $($systemModel.ExternalSystems.Count)",
                "Scope: high-level system context"
            )
            $generatedFiles += "[C4 Context](diagrams/c4-context.md)"
            Write-Host "Generated: $contextOutput" -ForegroundColor Green
        }
    }
}

if ($DiagramLevels -in @('Container', 'All')) {
    $containerOutput = Join-Path $diagramsPath "c4-container.md"
    if ((Test-Path $containerOutput) -and -not $Force) {
        Write-Host "Container diagram already exists (use -Force to regenerate)" -ForegroundColor Gray
    }
    else {
        $containerModel = Build-ContainerModel -SolutionPath $solutionFile
        if ($containerModel) {
            $mermaid = New-ContainerMermaid -ContainerModel $containerModel
            Save-MermaidMarkdown -FilePath $containerOutput -Title "C4 Container" -Mermaid $mermaid -Summary @(
                "System: $($containerModel.SystemName)",
                "Containers detected: $($containerModel.Containers.Count)",
                "Relationships detected: $($containerModel.Relationships.Count)"
            )
            $generatedFiles += "[C4 Container](diagrams/c4-container.md)"
            Write-Host "Generated: $containerOutput" -ForegroundColor Green
        }
    }
}

$overviewPath = Join-Path $OutputPath "overview.md"
if ($generatedFiles.Count -gt 0) {
    Update-OverviewArchitectureSection -OverviewPath $overviewPath -References $generatedFiles
    Write-Host "Updated overview architecture section" -ForegroundColor Green
}

Write-Host "`n✓ Mermaid C4 diagram generation complete" -ForegroundColor Green
