#
# generate-docs-index.ps1
#
# Purpose: Generates a navigation index for all documentation artifacts. Creates a landing page
#          with links to all generated documentation files, making it easy for users to discover
#          and navigate the documentation set.
#
# Usage: .\generate-docs-index.ps1 -RootPath <target_codebase_path>
# Output: Writes to AppDoc/docs/index.md (relative to RootPath)
#

param(
    [Parameter(Mandatory=$true)]
    [string]$RootPath
)

Write-Host "📑 Generating Documentation Index..." -ForegroundColor Cyan

# Validate root path
if (-not (Test-Path $RootPath)) {
    Write-Error "Root path does not exist: $RootPath"
    exit 1
}

Write-Progress -Activity "Generating Documentation Index" -Status "Reviewing artifacts..." -PercentComplete 0

$docsPath = Join-Path $RootPath "docs"
$artifacts = @(
    @{ File = "overview.md"; Title = "System Overview"; Description = "High-level codebase summary" },
    @{ File = "api-inventory.md"; Title = "API Inventory"; Description = "All API endpoints and contracts" },
    @{ File = "data-model.md"; Title = "Data Model"; Description = "Data structures and relationships" },
    @{ File = "config-catalog.md"; Title = "Configuration Catalog"; Description = "All configuration options" },
    @{ File = "build-cookbook.md"; Title = "Build Cookbook"; Description = "Build and deployment commands" },
    @{ File = "test-catalog.md"; Title = "Test Catalog"; Description = "Test suites and cases" },
    @{ File = "debt-register.md"; Title = "Technical Debt Register"; Description = "Known technical debt items" }
)

$markdown = "# Documentation Index`n`n"
$markdown += "**Generated**: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`n`n"
$markdown += "This is the complete documentation set for the codebase. Select a document below to explore specific aspects of the system.`n`n"
$markdown += "## Available Documentation`n`n"

$foundCount = 0
foreach ($artifact in $artifacts) {
    $path = Join-Path $docsPath $artifact.File
    if (Test-Path $path) {
        $markdown += "### [$($artifact.Title)]($($artifact.File))`n"
        $markdown += "$($artifact.Description)`n`n"
        $foundCount++
    }
}

if ($foundCount -eq 0) {
    $markdown += "_No documentation artifacts found yet. Run the AppDoc workflow to generate documentation._`n`n"
}

$markdown += "---`n`n"
$markdown += "**Total Documents**: $foundCount / $($artifacts.Count)`n`n"
$markdown += "**Generated by AppDoc Framework**`n"

Write-Progress -Activity "Generating Documentation Index" -Status "Creating index..." -PercentComplete 50

$indexPath = Join-Path $docsPath "index.md"
$markdown | Out-File -FilePath $indexPath -Encoding UTF8

Write-Progress -Activity "Generating Documentation Index" -Status "Complete" -PercentComplete 100
Write-Host "✅ Documentation index generated: $indexPath" -ForegroundColor Green
Write-Host "   Documents indexed: $foundCount / $($artifacts.Count)" -ForegroundColor Gray
